### ISSUE TITLE
bing set -d ~/Obrázky/ gnome

### ISSUE THREAD

**Issue by ge0rgecz** [lord63/wonderful_bing#22]
`Traceback (most recent call last):
  File "/usr/local/bin/bing", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/wonderful_bing/wonderful_bing.py", line 159, in main
    wonderful_bing = WonderfulBing(arguments)
  File "/usr/local/lib/python2.7/dist-packages/wonderful_bing/wonderful_bing.py", line 126, in __init__
    self.picture_path = path.join(self.directory, self.bing.picture_name)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)`

**Comment by lord63** [comment]
Try v0.10.0, sorry for the unbelievable delay.
